"""add job_tracker_items and fix missing columns

Revision ID: f698d93c784f
Revises: d05f5b4e3dec
Create Date: 2026-07-09 21:58:02.464498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f698d93c784f'
down_revision: Union[str, Sequence[str], None] = 'd05f5b4e3dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_tracker_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tracker_items_id'), 'job_tracker_items', ['id'], unique=False)
    # NOTE: jobs, user_roles, profiles, interview_questions, applications tables
    # are legacy Supabase tables not managed by this ORM — do NOT drop them.
    op.drop_constraint('ats_scores_resume_id_fkey', 'ats_scores', type_='foreignkey')
    op.create_foreign_key(None, 'ats_scores', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chatbot_history_user_id_fkey', 'chatbot_history', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('cover_letters', sa.Column('tone', sa.String(), nullable=True))
    op.drop_constraint('cover_letters_user_id_fkey', 'cover_letters', type_='foreignkey')
    op.create_foreign_key(None, 'cover_letters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('interview_answers_session_id_fkey', 'interview_answers', type_='foreignkey')
    op.create_foreign_key(None, 'interview_answers', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('interview_sessions', sa.Column('technical_score', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('communication_score', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.drop_constraint('interview_sessions_user_id_fkey', 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_matches_resume_id_fkey', 'job_matches', type_='foreignkey')
    op.drop_constraint('job_matches_user_id_fkey', 'job_matches', type_='foreignkey')
    op.create_foreign_key(None, 'job_matches', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_matches', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('learning_roadmaps', sa.Column('current_skills', sa.Text(), nullable=True))
    op.drop_constraint('learning_roadmaps_user_id_fkey', 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'learning_roadmaps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('resume_analysis_resume_id_fkey', 'resume_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'resume_analysis', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'resume_analysis', type_='foreignkey')
    op.create_foreign_key('resume_analysis_resume_id_fkey', 'resume_analysis', 'resumes', ['resume_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'learning_roadmaps', type_='foreignkey')
    op.create_foreign_key('learning_roadmaps_user_id_fkey', 'learning_roadmaps', 'users', ['user_id'], ['id'])
    op.drop_column('learning_roadmaps', 'current_skills')
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.create_foreign_key('job_matches_user_id_fkey', 'job_matches', 'users', ['user_id'], ['id'])
    op.create_foreign_key('job_matches_resume_id_fkey', 'job_matches', 'resumes', ['resume_id'], ['id'])
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key('interview_sessions_user_id_fkey', 'interview_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('interview_sessions', 'confidence_score')
    op.drop_column('interview_sessions', 'communication_score')
    op.drop_column('interview_sessions', 'technical_score')
    op.drop_constraint(None, 'interview_answers', type_='foreignkey')
    op.create_foreign_key('interview_answers_session_id_fkey', 'interview_answers', 'interview_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.create_foreign_key('cover_letters_user_id_fkey', 'cover_letters', 'users', ['user_id'], ['id'])
    op.drop_column('cover_letters', 'tone')
    op.drop_constraint(None, 'chatbot_history', type_='foreignkey')
    op.create_foreign_key('chatbot_history_user_id_fkey', 'chatbot_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ats_scores', type_='foreignkey')
    op.create_foreign_key('ats_scores_resume_id_fkey', 'ats_scores', 'resumes', ['resume_id'], ['id'])
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('applied', 'screening', 'shortlisted', 'interview_scheduled', 'rejected', 'approved', name='application_status'), server_default=sa.text("'applied'::application_status"), autoincrement=False, nullable=False),
    sa.Column('ai_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_concerns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matching_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('missing_skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('match_recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['auth.users.id'], name='applications_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='applications_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='applications_pkey'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='applications_job_id_candidate_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='interview_questions_application_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], name='interview_questions_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='interview_questions_pkey')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='profiles_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('candidate', 'recruiter', 'hiring_manager', name='app_role'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_roles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey'),
    sa.UniqueConstraint('user_id', 'role', name='user_roles_user_id_role_key')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'closed', name='job_status'), server_default=sa.text("'open'::job_status"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('experience_required', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], name='jobs_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey')
    )
    op.drop_index(op.f('ix_job_tracker_items_id'), table_name='job_tracker_items')
    op.drop_table('job_tracker_items')
    # ### end Alembic commands ###
